import { useNavigate } from "react-router-dom";
export default function Module2() {
  



  const navigate = useNavigate();
  return (
    <div style={{ padding: "20px" }}>
      <h1>Password Security</h1>

      <p>
        Strong passwords should contain uppercase, lowercase, numbers,
        and symbols.
      </p>

      <p>
        Password security is one of the most fundamental building blocks of staying safe online, yet it's also one of the 
        most commonly neglected. The core problem is that people tend to create passwords that are easy for them to 
        remember — which unfortunately also makes them easy for attackers to guess or crack. Simple passwords 
        like "password123" or "john1990" can be broken in seconds using automated tools that run through millions of common combinations.
        Even more dangerous is password reuse — using the same password across multiple accounts means that if one site gets breached, 
        attackers can use those same credentials to break into your email, bank, or social media. This technique is called credential stuffing, 
        and it's extremely common.
      </p>

      <p>
        A strong password has a few key qualities: it's long (at least 12-16 characters), random (not based on real words, names, or dates), 
        and unique to each account. A passphrase — a string of random words like "PurpleCactus!RiverBoot42" — can be both 
        strong and memorable. The randomness matters more than complexity; a long, random passphrase is far stronger than a short password 
        with a few symbols swapped in. Avoid anything tied to personal information that someone could find or guess, like birthdays, pet names, or your 
        favorite sports team.
      </p>

      <p>
        The single best tool for managing password security is a password manager. Apps like Bitwarden, 1Password, or Dashlane 
        generate and store long, random, unique passwords for every single account you have — you only need to remember one strong
         master password. This completely eliminates the temptation to reuse passwords and takes the mental burden off of
        you entirely. Most password managers also alert you if one of your saved passwords shows up in a known data breach, so 
        you can change it before any damage is done. They work across devices and browsers, making the experience pretty seamless once 
        you're set up.
      </p>
      <p>
        Beyond the password itself, two-factor authentication (2FA) adds a critical second layer of protection. Even if your password is 
        somehow stolen, an attacker still can't get in without that second factor — usually a code sent to your phone or generated by an app 
        like Google Authenticator or Authy. Whenever a service offers 2FA, turn it on, especially for high-value accounts like email, banking, 
        and anything tied to your identity. Email in particular is worth prioritizing, since it's often used to reset passwords on other 
        accounts — if an attacker gets into your email, they can potentially chain their way into everything else. Think of 2FA as a 
        deadbolt on a door that already has a lock — even if someone picks the lock, they're still not getting in.
      </p>
     <button
        onClick={() => navigate("/quiz")}
        style={{
          marginTop: "30px",
          padding: "10px 20px",
          cursor: "pointer"
        }}
      >
        Take Quiz
      </button>

    </div>
  );
}
